            -名称：上传构建工件
  用途：Actions/upload-artifact@v4.6.0用途：Actions/upload-artifact@v4.6.0
  和：
    ＃工件名称
    名称：＃可选，默认为伪影
    ＃描述上传内容的文件，目录或通配符模式
    小路：
    ＃如果使用提供的路径找不到文件，则所需的行为。，则所需的行为。，则所需的行为。，则所需的行为。
可用选项：
  警告：输出警告，但不要使动作失败
  错误：没有错误消息使操作失败
  忽略：不要输出任何警告或错误，动作不会失败

    如果不是文件：＃可选，默认值为警告
    ＃持续时间在几天内将过期。 0表示使用默认保留。
至少1天。最多90天，除非从“存储库设置”页面更改。

    保留日：＃可选
    ＃将 Zlib的压缩级别应用于工件档案。该值的范围从0到9：-0：无压缩-1：最佳速度-6：默认压缩（与 gnu gzip相同） -  9：最佳压缩较高：最佳压缩较高：最佳压缩较高级别将导致更好的压缩，但需要更长的时间才能完成。对于不容易压缩的大型文件，建议将，0值为0，以更快地上传。

    压缩级别：＃可选，默认值为6
    ＃如果是的，则将在上传新名称之前删除带有匹配名称的工件。如果是错误的，则如果给定名称的工件已经存在，则该动作将失败。如果不存在工件，则不会失败。

    覆盖：＃可选，默认值为false
    ＃如果为 true，则隐藏的文件将包含在工件中。如果是错误的，则隐藏的文件将被排除在工件之外。，则隐藏的文件将被排除在工件之外。

    包括隐藏的文件：＃可选，默认值为false
          
